<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="welcome-PC" name="testCases.TestSoftAssertions" tests="1" failures="1" timestamp="12 Jun 2018 06:19:44 GMT" time="0.096" errors="0">
  <testcase name="doRegisterTest" time="0.096" classname="testCases.TestSoftAssertions">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [xxxxxxx] but found [yyyyyyy],
	expected [c] but found [a]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [xxxxxxx] but found [yyyyyyy],
	expected [c] but found [a]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testCases.TestSoftAssertions.doRegisterTest(TestSoftAssertions.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- doRegisterTest -->
</testsuite> <!-- testCases.TestSoftAssertions -->
